version: '3'

services:
  server:
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    image: synerex_server
    environment:
      - SX_SERVER_HOST=server
      - SX_NODESERV_HOST=nodeserv
      - SX_PUBLIC_KEY=8AAC2286D4448FAD779F147357BFF
      - SX_PRIVATE_KEY=61268C659CAADC95C8DFB41399C12
    depends_on:
      - "nodeserv"
    volumes:
      - ./server:/go/src/github.com/synerex_server
    ports:
      - "10000:10000"
    networks: 
      - synerex_net
      - default
  nodeserv:
    tty: true
    build:
      context: ./nodeserv
      dockerfile: Dockerfile
    image: synerex_nodeserv
    volumes:
      - ./nodeserv:/go/src/github.com/synerex_nodeserv
    ports:
      - "9990:9990"
    networks: 
      - synerex_net
      - default
networks:
  synerex_net:
    external: true
